# These are supported funding model platforms

github: [alexzeecomedy]
patreon: alexzeecomedy
open_collective: # Replace with a single Open Collective username
ko_fi: alexzeecomedy
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: alexzeecomedy
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: alexzeecomedy
thanks_dev: # Replace with a single thanks.dev username
custom: ['https://rc.wishthis.online/wishlist/8d8438f00d2ae7301f81c903e9105e99ff35bcc7', 'https://www.amazon.com/hz/wishlist/ls/1LVKOJC7FL2Q', 'https://cash.app/$alexzeecomedy', 'https://venmo.com/u/alexzeecomedy']
